### ISSUE TITLE
Links on HTTPS websites

### ISSUE THREAD

**Issue by toplisek** [linkcheck/linkchecker#134]
I'm not sure but I can not check links on HTTPS websites
 links at HTTPS websites.
Is this possible to be fixed? I like this software as it one of the best but HTTPs seems not to be supported. How to validate links when using HTTPS secured links.
Thank you.

**Comment by anarcat** [comment]
https works fine. 

```
$ linkchecker https://google.com/
INFO linkcheck.cmdline 2018-03-23 08:57:12,140 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.4              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2018-03-23 08:57:12-004

Statistics:
Downloaded: 1KB.
Content types: 0 image, 1 text, 0 video, 0 audio, 1 application, 0 mail and 1 other.
URL lengths: min=34, max=62, avg=50.

That's it. 3 links in 4 URLs checked. 0 warnings found. 0 errors found.
Stopped checking at 2018-03-23 08:57:12-004 (0.78 seconds)
```

please explain in more details the problems you are seeing.

**Comment by toplisek** [comment]
I do nto see version 9.4. Can you post a link to download 9.4.?
An error message:
[
![linkchecker_issue_https](https://user-images.githubusercontent.com/4067542/37831339-6a4ac338-2ea5-11e8-9d7a-7436482dfe46.jpg)
]

**Comment by anarcat** [comment]
9.4 is not released yet, afaik.

there's a configuration problem with the https link you are following. linkchecker currently does not support bypassing HTTPS links. in fact, I would argue that it should that the link is broken and that linkchecker is behaving as designed. :)

**Comment by toplisek** [comment]
Website is working and all links checked. What kind of a configuration problem you see?

**Comment by anarcat** [comment]
ah, well if the site is working in a normal web browser, this is a different problem.  this looks like #106, so I suggest you followup there with more information.
