### ISSUE TITLE
9.4.0 release

### ISSUE THREAD

**Issue by anarcat** [linkcheck/linkchecker#141]
I figured I would *finally* perform a release even if we're not in a position to upload it to PyPI. At least it can be sync'd to Debian and people can rely on the tag instead of master in CI and git-based deployments. I'm tracking that work here, since we haven't made many of those.

**Comment by anarcat** [comment]
The first hurdle i found is that tests fail on my desktop (#140). That's not a big deal because it's only a problem with the test suite (hopefully?) and tests pass on travis, so we can ignore that for now.

But more importantly, I can't figure out how to actually push the release now. I edited the changelog and release process to note that we need to do that on release (and we should ask people making PRs to update the changelog too, btw). But now I can't push to master because of our restrictions.

**Comment by anarcat** [comment]
okay, so I broke the rules: i disabled the branch restrictions for the "master" branch in order to push the release. i don't see how to do this otherwise: the change to the files is trivial and i don't know if it would really require a pull request review. besides, i don't know if a pull request can merge a tag, and everyone has been waiting for so long for this release that I don't feel it's right to have the rules block me when I finally find the time to try and fix up a release.

so now we have a new release, yaaay!

```
[265]anarcat@curie:linkchecker1$ git push 
warning: pas d'envoi de certificat de poussée car le receveur ne gère pas les poussées avec --signed
Décompte des objets: 6, fait.
Delta compression using up to 4 threads.
Compression des objets: 100% (6/6), fait.
Écriture des objets: 100% (6/6), 1.39 KiB | 0 bytes/s, fait.
Total 6 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To github.com:linkcheck/linkchecker.git
   c992bd7a..afad6c80  master -> master
[266]anarcat@curie:linkchecker$ git push --tags
warning: pas d'envoi de certificat de poussée car le receveur ne gère pas les poussées avec --signed
Total 0 (delta 0), reused 0 (delta 0)
To github.com:linkcheck/linkchecker.git
 * [new tag]           v9.4.0 -> v9.4.0
```

i would very much welcome advice on how to do this better the next time, i hope i didn't break anything either... :/

**Comment by anarcat** [comment]
one thing I realized i screwed up is the title of the release in the changelog file: there's no date and the title is an empty string.

i think we may want to drop that practice anyways, releases should be as easy as possible. we can still keep the tradition going in github release notes, but i don't think it's necessary in the changelog itself.

**Comment by anarcat** [comment]
next up is the debian package upload, stay tuned!

**Comment by anarcat** [comment]
phew. the debian package was in dire shape! i think i managed to build something meaningful, but there's horrible horrible things lurking in there. hopefully the upload will fix a bunch of stuff, but there are still a few open bugs on Debian's side regarding the webserver configuration which I haven't had time to fix.

i consider the release as good as it gets for now. of course it's still not on PyPI, but the tag should help some people at least.

**Comment by anarcat** [comment]
oh, and i restored the branch protection for admins. i guess we could proceed like this next time as well: when we need to make a release, we turn off the protection just while we push the tags and small documentation changes, temporarily.

**Comment by anarcat** [comment]
i opened #142 to cleanup the repository, because the files in doc/web created problems within the debian package... this was fixed by a hack in `debian/source/options` but that shouldn't be necessary.

**Comment by anarcat** [comment]
for what that's worth, the debian package lives in the debian branch here still.

**Comment by mgedmin** [comment]
I like [zest.releaser](https://pypi.org/project/zest.releaser/) for automating releases.  It takes care of updating versions and dates in changelogs and `setup.py`.  (And it's modular, so you can do the version bump automation separately from `twine upload` or whatever the main release step is.)

Branch protections interfere with release automation tools, which is why I tend to keep the `master` branch unprotected and rely on people not making mistakes.  (I sometimes make mistakes and push things to master that should've gone to a branch.)  I don't know what a good solution is.

**Comment by anarcat** [comment]
Thanks for the tip!

Maybe we can stick with the process where we unprotect the branch on release?

I did not know about zest.releaser, it looks interesting! How does that compare with [versioneer](https://pypi.python.org/pypi/versioneer), by the way?

As you might have seen, I personally prefer avoiding version numbers in code and instead rely on version control or packaging to give us version numbers. Unfortunately, this can break down pretty badly with `pkg_resources`, but in the case of linkchecker I am not sure the ~200ms startup delay is such a big deal... So I would tend to lean towards `setuptools_scm` rather than more manual stuff, even if it's an "automated manual process" :)

**Comment by anarcat** [comment]
i'm happy with any improvement, in any case. :) as long as the process is documented and works reliably, of course. :)
