### ISSUE TITLE
support $XDG_CONFIG_HOME / $XDG_DATA_HOME

### ISSUE THREAD

**Issue by legrostdg** [linkcheck/linkchecker#44]
It would be great if linkchecker could support $XDG_CONFIG_HOME / $XDG_DATA_HOME.

**Comment by anarcat** [comment]
yeah, it sure would! :)

**Comment by legrostdg** [comment]
fixed by #87

**Comment by legrostdg** [comment]
Could we expect a new release anytime soon?

**Comment by anarcat** [comment]
see #4
