### ISSUE TITLE
gh-pages reports failing build

### ISSUE THREAD

**Issue by kyleshrader** [linkcheck/linkchecker#67]
gh-pages is currently reporting the status of https://travis-ci.org/wummel/linkchecker. Please update this to report the status of https://travis-ci.org/linkcheck/linkchecker

**Comment by kyleshrader** [comment]
It seems there are numerous references in gh-pages that need to be changed, now that you've moved to http://www.github.com/linkcheck

**Comment by anarcat** [comment]
i believe this was fixed in #144.
