### ISSUE TITLE
Linkchecker fails with "Oops, I did it again"

### ISSUE THREAD

**Issue by JAremko** [linkcheck/linkchecker#74]
Suddenly Linkchecker [stopped to work](https://travis-ci.org/syl20bnr/develop.spacemacs.org/builds/245720094?utm_source=github_status&utm_medium=notification) We are using [this docker image](https://github.com/JAremko/docker-linkchecker/blob/master/Dockerfile)

Can you make it green again? :thinking:

**Comment by JAremko** [comment]
This is a [recent build log](https://hub.docker.com/r/jare/linkchecker/builds/b6spgxn4k6yweow5tcwzezb/) and this is an [old one](https://hub.docker.com/r/jare/linkchecker/builds/buyy2k2vwracugf6yu4bfkw/) (that was working)

**Comment by JAremko** [comment]
"fixed" in #74

**Comment by anarcat** [comment]
i take it you mean #75?

**Comment by JAremko** [comment]
@anarcat  :smile:

**Comment by anarcat** [comment]
see #76 for a more accurate title and followup.
