### ISSUE TITLE
No binary file

### ISSUE THREAD

**Issue by mrkaban** [linkcheck/linkchecker#92]
Hello, I have a few questions! I see a binary file not yet, when will it appear?

Plus in the previous page I wrote a request like this: https://github.com/wummel/linkchecker/issues/725#issuecomment-340247606

I want to say that the program is cool, and enjoys some popularity on my site, here is the [link](https://континентсвободы.рф/%D1%81%D0%B5%D1%82%D1%8C,-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/linkchecker-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D0%B1%D0%B8%D1%82%D1%8B%D1%85-%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D0%BA-%D0%BD%D0%B0-%D1%81%D0%B0%D0%B9%D1%82%D0%B5.html).

**Comment by anarcat** [comment]
i'm not sure i understand your question, but I'll assume you're asking "when is the next release?"

we are still trying to figure out how to make a PyPI release using the old name, which seems impossible for now, see https://github.com/linkcheck/linkchecker/issues/4.

as for wummel/linkchecker#725, could you please open a separate issue? thanks.
