### ISSUE TITLE
Unbundle dnspython and miniboa

### ISSUE THREAD

**Issue by arunisaac** [linkcheck/linkchecker#95]
Hi,

I have packaged linkchecker for GuixSD.

Currently, modified versions of dnspython and miniboa come bundled with linkchecker in third_party/. Unbundling them would enable GuixSD to treat them as separate dependencies, and package linkchecker more easily. Could you please do this? You could contribute any changes upstream, and/or write necessary wrappers around those libraries.

Thank you!

**Comment by anarcat** [comment]
i believe this was done in #118 by @PetrDlouhy and released as part of 9.4.0.
